import "./ModernGrey/index.css"
import "./ModernGrey/App.css"
import "./ModernGrey/Custom-fonts.css"
import "./ModernGrey/Exchange.scss"
import "./ModernGrey/FoundationalEvents.scss"
import "./ModernGrey/initiation.scss"
import "./ModernGrey/managment.scss"
import "./ModernGrey/MapOverlay.css"
import "./ModernGrey/MapStyles.scss"
import "./ModernGrey/Portfolio.scss"
import "./ModernGrey/root.css"
import "./ModernGrey/styles.css"
import "./ModernGrey/TheCoin.scss"
import "./ModernGrey/TheToken.scss"
import "./ModernGrey/Slider.scss"
export default function ModernGreyStyling(props) { }